#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://KendallWMiller.com" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page/:num"

#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  talks:
    output: true
    permalink: /talks/:slug
  work:
    output: true
    permalink: /work/:slug
    order:
      - fileandservexpress.md
      - gibraltar.md
      - benelogic.md

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"

sass:
  sass_dir: _sass
  style: compressed